#pragma once

#include <credentialprovider.h>

enum FIELD_ID
{
	FID_LOGO,
	FID_LARGE_TEXT,
	FID_SMALL_TEXT,
	FID_USERNAME,
	FID_PASSWORD,
	FID_FIDO_PIN,
	FID_NEW_PASS_1,
	FID_NEW_PASS_2,
	FID_SUBMIT_BUTTON,
	FID_NUM_FIELDS
};

struct FIELD_STATE_PAIR
{
	CREDENTIAL_PROVIDER_FIELD_STATE cpfs;
	CREDENTIAL_PROVIDER_FIELD_INTERACTIVE_STATE cpfis;
};

static const FIELD_STATE_PAIR s_rgScenarioUsernamePassword[FID_NUM_FIELDS] =
{
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_FOCUSED },
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },
	{ CPFS_HIDDEN, CPFIS_NONE },
	{ CPFS_HIDDEN, CPFIS_NONE },
	{ CPFS_HIDDEN, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE }
};

static const FIELD_STATE_PAIR s_rgScenarioFido[FID_NUM_FIELDS] =
{
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },
	{ CPFS_HIDDEN, CPFIS_NONE },
	{ CPFS_HIDDEN, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_FOCUSED },
	{ CPFS_HIDDEN, CPFIS_NONE },
	{ CPFS_HIDDEN, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE }
};

static const FIELD_STATE_PAIR s_rgScenarioChangePassword[FID_NUM_FIELDS] =
{
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_BOTH, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },
	{ CPFS_HIDDEN, CPFIS_NONE },
	{ CPFS_HIDDEN, CPFIS_NONE },
	{ CPFS_HIDDEN, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_FOCUSED },
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },
	{ CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE }
};

static CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR s_rgScenarioCredProvFieldDescriptors[FID_NUM_FIELDS] =
{
	{ FID_LOGO, CPFT_TILE_IMAGE, const_cast<LPWSTR>(L"") },
	{ FID_LARGE_TEXT, CPFT_LARGE_TEXT, const_cast<LPWSTR>(L"Windows FIDO Logon") },
	{ FID_SMALL_TEXT, CPFT_SMALL_TEXT, const_cast<LPWSTR>(L"") },
	{ FID_USERNAME, CPFT_COMBOBOX, const_cast<LPWSTR>(L"Local user") },
	{ FID_PASSWORD, CPFT_PASSWORD_TEXT, const_cast<LPWSTR>(L"Windows password") },
	{ FID_FIDO_PIN, CPFT_PASSWORD_TEXT, const_cast<LPWSTR>(L"Security key PIN") },
	{ FID_NEW_PASS_1, CPFT_PASSWORD_TEXT, const_cast<LPWSTR>(L"New Windows password") },
	{ FID_NEW_PASS_2, CPFT_PASSWORD_TEXT, const_cast<LPWSTR>(L"Confirm new password") },
	{ FID_SUBMIT_BUTTON, CPFT_SUBMIT_BUTTON, const_cast<LPWSTR>(L"") }
};
